### ISSUE TITLE
Passenger specific code in ngix config

### ISSUE THREAD

**Issue by hudakh** [engineyard/ey-cookbooks-stable-v6#117]
https://github.com/engineyard/ey-cookbooks-stable-v6/blob/5c70b7aa9da4d20ae9875c2529dd7018855f9838/cookbooks/nginx/templates/default/nginx_app.conf.erb#L97 appears to be a `messenger` specific change, and needs to be conditional on `passenger` being in use.

**Comment by DalianisDim** [comment]
Thanks for reporting. Will be fixed as part of https://github.com/engineyard/ey-cookbooks-stable-v6/pull/122
