### ISSUE TITLE
Sphinx recipe

### ISSUE THREAD

**Issue by hudakh** [engineyard/ey-cookbooks-stable-v6#120]
The `thinking_sphinx` recipes and custom recipes are available in `ey-bookbooks-stable-v5`. Where are they in v6?

**Comment by DalianisDim** [comment]
@hudakh, `thinking_sphinx` is yet to be ported to Stack V6. We are working in that and expect a PR anytime soon.

**Comment by hudakh** [comment]
Is this still in the pipeline?

**Comment by pasanchamikara** [comment]
@hudakh TS3 for stack-v6 is released with EY's latest stack-v6 release, you can follow the mentioned instructions for setting it up. https://github.com/engineyard/ey-cookbooks-stable-v6/blob/next-release/custom-cookbooks/thinking_sphinx_3/custom-thinking_sphinx_3/README.md
