### ISSUE TITLE
resque PATH should contain the bundler location

### ISSUE THREAD

**Issue by giannoul** [engineyard/ey-cookbooks-stable-v6#123]
In v6 the bundler is installed under `/opt/rubies/ruby-x.x.x/bin`. This location should be also exist in the PATH variable set on the line 7 in the file `resque/files/default/resque.rb`.

**Comment by DalianisDim** [comment]
As per https://github.com/engineyard/ey-cookbooks-stable-v6/pull/124#issuecomment-529731396, this is not an issue, therefore I'm closing it. Quoting the comment here:

> @mushyy have you seen any errors with resque starting? Even without ruby on the path on the resque script, resque should start because we use `bash -l` on the monit script
> 
> https://github.com/engineyard/ey-cookbooks-stable-v6/blob/a2d173fe58adda5cc1bcf4c8b3b31e0ceb129a16/cookbooks/resque/templates/default/monitrc.conf.erb#L4
> 
> Using `-l` or `--login` will add ruby to the path (see /etc/profile.d/chruby.sh)
> 
> If we still want to add ruby to the resque script, I think we should use `/opt/rubies/ruby-#{node[:ruby][:version]}/bin` instead of `which`.
