### ISSUE TITLE
Add a `yarn` recipe

### ISSUE THREAD

**Issue by frederikspang** [engineyard/ey-cookbooks-stable-v6#127]
Support for Yarn, as implemented in v5 in https://github.com/engineyard/ey-cookbooks-stable-v5/pull/390

**Comment by DalianisDim** [comment]
@frederikspang we are approaching the issue differently on Stack V6, please have a look in PR https://github.com/engineyard/ey-cookbooks-stable-v6/pull/132

**Comment by frederikspang** [comment]
Great! Can't wait to have this released!
