### ISSUE TITLE
Solr recipe

### ISSUE THREAD

**Issue by kirillplatonov** [engineyard/ey-cookbooks-stable-v6#158]
The `solr` recipe was available in `ey-cookbooks-stable-v5`. Any chances it will be ported to v6?

**Comment by mushyy** [comment]
I wrote one out a while ago as a custom recipe for v6 I shall do a PR after some more testing and close this out when its been approved.

**Comment by kirillplatonov** [comment]
@mushyy sounds great! Let me know if there's anything I can do to help you with it!
